### PR TITLE
Chore: change license to MIT

### PR DESCRIPTION
**Pull request by JPeer264**
Since [smartwrap](https://github.com/tecfu/smartwrap) has also changed to MIT I hope it is ok to also change the license here to MIT.

### CODE REVIEW

**Comment by JPeer264** [comment]
@tecfu thanks for the quick update. Could you also update the npm package please, then the license is also updated on the latest npm package. Thanks in advance 👍

**Comment by Andarist** [comment]
@tecfu just a friendly ping that this could be released to npm, no rush though

**Comment by tomonari-t** [comment]
+1

**Comment by tomonari-t** [comment]
plz release this to NPM

**Pull request merged**
